-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTOL_ORDER
FROM ICECREAM_INFO I RIGHT JOIN FIRST_HALF F ON I.FLAVOR = F.FLAVOR 
GROUP BY INGREDIENT_TYPE
#SELECT * FROM dept d LEFT OUTER JOIN emp e ON d.deptno = e.deptno; 